version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pact-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: psql postgres -U postgres --command 'SELECT 1'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  
  broker:
    image: pactfoundation/pact-broker:latest-multi
    container_name: pact-broker
    depends_on:
      - postgres
    ports:
      - "9292:9292"
    restart: always
    environment:
      PACT_BROKER_ALLOW_PUBLIC_READ: "false"
      PACT_BROKER_BASIC_AUTH_USERNAME: admin
      PACT_BROKER_BASIC_AUTH_PASSWORD: pass
      PACT_BROKER_DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"

    healthcheck:
      test: ["CMD", "curl", "--silent", "--show-error", "--fail",
             "http://pactbroker:pactbroker@localhost:9292/diagnostic/status/heartbeat"]
      interval: 1s
      timeout: 2s
      retries: 5